# Generated by Django 5.2.1 on 2025-05-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(upload_to='circuits/')),
                ('itineraire', models.TextField()),
                ('points_interet', models.TextField()),
                ('duree', models.PositiveIntegerField(help_text='Durée en jours')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destinations/')),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('disponibilites', models.PositiveIntegerField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='voyages.circuit')),
            ],
            options={
                'ordering': ['date_depart'],
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='voyages.destination'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voyages.circuit')),
            ],
        ),
    ]
