# Generated by Django 5.2.1 on 2025-05-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_reservation_reservationoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('CB', 'Carte bancaire'), ('virement', 'Virement'), ('espece', 'Espèces')], max_length=30)),
                ('statut', models.CharField(choices=[('effectue', 'Effectué'), ('en_attente', 'En attente')], default='effectue', max_length=20)),
                ('acompte', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='voyages.reservation')),
            ],
        ),
    ]
